### ISSUE TITLE
Space only

### ISSUE THREAD

**Issue by Venominside** [goodideagiver/roadmapper-ts#2]
**Describe the bug**

/You can add title using only spaces.

**To Reproduce**
1. Go to '[...](https://goodideagiver.github.io/roadmapper-ts/)'
2. Click on 'Add main roadmap point'
3. Find "Roadmap title"
4. Use space to set title

**Expected behavior**

/"Error: Invalid characters" or smth

**Screenshots**

/
![obraz](https://user-images.githubusercontent.com/49470841/179193348-0afb5011-d523-4f13-9c5f-037e3f216a87.png)

**Additional context**

/xoxo

**Comment by goodideagiver** [comment]
ebf0a3d07ebdcf43a65aaabbb81f4f988f4dc053
