### ISSUE TITLE
Midpoint title

### ISSUE THREAD

**Issue by Venominside** [goodideagiver/roadmapper-ts#5]
**Describe the bug**

/Can't edit midpoint title

**To Reproduce**
2. Click on any point.
3. Click on 'add midpoint'
4. Set title and duration
5. Click on 'Confirm roadmap point'
6. Find any midpoint and click on 'edit' on it
7. Try to change title

**Expected behavior**

/change title

**Screenshots**

![obraz](https://user-images.githubusercontent.com/49470841/179199298-fc8732a7-1408-4cbf-b355-e1def3f81049.png)

**Additional context**
/xoxo

**Comment by Venominside** [comment]
I don't see any consequences since the title of the main point can be edited

**Comment by goodideagiver** [comment]
Added edit feature 271a2ae1b2d447582fc6d48333097528c7c5e329
