### ISSUE TITLE
Text overlaps

### ISSUE THREAD

**Issue by Venominside** [goodideagiver/roadmapper-ts#9]
**Describe the bug**
Text in title overlaps if it's too long

**To Reproduce**
1. Go to 'add roadmap point'
2. Click on 'roadmap point title'
3. Type 14< characters

**Expected behavior**
No overlaps

**Screenshots**
![obraz](https://user-images.githubusercontent.com/49470841/182333588-f22a32dc-7510-4991-bd55-30926d814aaf.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox

**Additional context**
xoxo

**Comment by goodideagiver** [comment]
Fixed by limiting input length 8de3d6ee033087a53c3dec67da2e2ce338424018
